name: lpg2
description: " Dart runtime for LPG2."

version: 1.0.0

homepage: "https://github.com/A-LPG/LPG-Dart-runtime"

license: "EPL-2.0 License"
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  dart_numerics: ^0.0.5

dev_dependencies:
  pedantic: ^1.10.0
